config/routes.rb
Rails.application.routes.draw do
  get 'shop/index'
  root 'shop#index'
  resources :categories do
    resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
		
		validates :name, presence: true,
    	length: { minimum: 5 }

		has_attached_file :image, styles: {big: ["535x300#", :jpeg], small: ["100x100#", :jpeg], original: [:jpeg]}
			
			validates_attachment :image,
        	content_type: { content_type: /\Aimage\/.*\z/ },
        	size: { less_than: 6.megabyte }
				
				validates :name, presence: true,
    			length: { minimum: 5 }
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category

	has_attached_file :image, styles: {big: ["535x300#", :jpeg], small: ["100x100#", :jpeg], original: [:jpeg]}

	validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 6.megabyte }

    validates :name, presence: true,
    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@category = Category.all
	end

	def show
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
	end

	def edit
		@category = Category.find(params[:id])
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			redirect_to @category
		else
			render 'new'
		end
	end

	def update
		@category = Category.find(params[:id])

		if @category.update(category_params)
		redirect_to @category
		else
		render 'edit'
		end			
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy

		redirect_to categories_path
	end

	private
	def category_params
		params.require(:category).permit(:name, :image)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_post, only: %i[show edit update destroy]

  def index
		@product = Product.all
	end

	def show; end

	def new
		@category = Category.find(params[:category_id])
    @product = Product.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @product }
		end
	end

	def edit; end

	def create
    @category = Category.find(params[:category_id])
		@product = @category.products.new(product_params)

		if @product.save
			# redirect_to [@category, @product]
			redirect_to @category
    else
      format.html { render :new }
      format.json { render json: @product.errors, status: :unprocessable_entity }
    end
	end

	def update

		if @product.update(product_params)
		redirect_to [@category, @product]
		else
		render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy

		redirect_to products_path
	end

	private

	def product_params
		params.require(:product).permit(:name, :image)
	end

	def set_list
		@category = Category.find(params[:category_id])
		@product = @category.products.find(params[:id])
	end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/categories/edit.html.erb
<h1>Editing...</h1>

<hr>

<%= form_with(model: @category, local: true) do |f| %>

	  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.file_field :image %>
		
	<%= link_to(image_tag(@category.image.url(:small)), @category.image.url, target: '_blank') if @category.image.exists? %>
	</p>

	<p>
		<%= f.submit %>
	</p>
	<% end %>

	

app/views/categories/index.html.erb
<strong>All Categories</strong>

<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th></th>
  </tr>

  <% @category.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= image_tag(category.image.url(:small)) %></td>
      <td> <hr> </td>
      <td><%= link_to 'Show', category_path(category) %></td>
      <td><%= link_to 'Edit', edit_category_path(category)%></td>
      <td><%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: 'TO4HO?'} %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category:</h1>

<hr>

<%= form_with scope: :category, url: categories_path, local: true do |f| %>

	  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.file_field :image %>
	</p>

	<p>
		<%= f.submit %>
	</p>
	<% end %>

	

app/views/categories/show.html.erb
<p>
	<%= link_to 'Categories', categories_path %> <br>
	<strong><%= @category.name %></strong><br>
		<hr>
			<%= image_tag(@category.image.url(:big)) if @category.image.exists? %>
			<%= link_to(image_tag(@category.image.url(:small)), @category.image.url, target: '_blank') if @category.image.exists? %>
</p>
<%= link_to 'new Product', new_category_product_path(@category)  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Editing...</h1>

<hr>

<%= form_with(model: @product, local: true) do |f| %>

	  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.file_field :image %>

	<%= link_to(image_tag(@product.image.url(:small)), @product.image.url, target: '_blank') if @product.image.exists? %>
	</p>

	<p>
		<%= f.submit %>
	</p>
	<% end %>

app/views/products/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th></th>
  </tr>

  <% @product.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= image_tag(product.image.url(:small)) %></td>
      <td> <hr> </td>
      <td><%= link_to 'Show', product_path(product) %></td>
      <td><%= link_to 'Edit', edit_product_path(product)%></td>
      <td><%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: 'TO4HO?'} %></td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h1>New Product:</h1>

<hr>

<%= form_for([@category, @product]) do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.file_field :image %>
	</p>

	<p>
		<%= f.submit %>
	</p>

	<% end %>

app/views/products/show.html.erb
<p>
	<%= link_to 'Products', category_product_path %> <br>
	<strong><%= @product.name %></strong><br>
		<hr>
			<%= image_tag(@product.image.url(:big)) if @product.image.exists? %>
			<%= link_to(image_tag(@product.image.url(:small)), @product.image.url, target: '_blank') if @category.image.exists? %>
</p>

app/views/shop/index.html.erb
<h1>My Shop!</h1>

<%= link_to 'Categories', categories_path %>